### ISSUE TITLE
where is the `demo_depth.py

### ISSUE THREAD

**Issue by pandamax** [hjimce/Depth-Map-Prediction#4]
Hi,where is the `demo_depth.py`?tx

**Comment by ixiaoli** [comment]
hello！@pandamax 
Are you find the "demo_depth.py"? I also meet the trouble.tx~

**Comment by liangwx** [comment]
一样

**Comment by liangwx** [comment]
same as 'weights/depth'...

**Comment by liangwx** [comment]
demo_depth.py is test.py here.Go  https://cs.nyu.edu/~deigen/depth/ for more details
